# Generated by Django 4.2.24 on 2025-09-11 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_api', '0003_order_transaction_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='productimage_id',
            new_name='product_image_id',
        ),
    ]
