# Generated by Django 4.2.24 on 2025-09-13 12:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('product_api', '0003_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySales',
            fields=[
                ('daily_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('total_sales_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_transactions', models.PositiveIntegerField(default=0)),
                ('total_stock_sold', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
