services:
  # Django Web App
  - type: web
    name: alx-project-nexus-web
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: gunicorn alx_project_nexus.wsgi:application
    postDeployCommand: |
      python manage.py migrate --noinput
      python manage.py create_default_superuser
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: alx-project-nexus-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: alx-project-nexus-redis
          type: redis
          property: connectionString
      - key: CACHE_URL
        fromService:
          name: alx-project-nexus-redis
          type: redis
          property: connectionString
      - key: SUPERUSER_NAME
        value: admin
      - key: SUPERUSER_EMAIL
        value: admin@example.com
      - key: SUPERUSER_PASSWORD
        value: 1234

  # Celery Worker
  - type: worker
    name: alx-project-nexus-worker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: celery -A alx_project_nexus worker --loglevel=info
    envVars:
      - key: SECRET_KEY
        fromService:
          name: alx-project-nexus-web
          type: web
          property: envVars.SECRET_KEY
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: alx-project-nexus-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: alx-project-nexus-redis
          type: redis
          property: connectionString
      - key: CACHE_URL
        fromService:
          name: alx-project-nexus-redis
          type: redis
          property: connectionString

  # Celery Beat (scheduler)
  - type: worker
    name: alx-project-nexus-beat
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: celery -A alx_project_nexus beat --scheduler django_celery_beat.schedulers:DatabaseScheduler --loglevel=info
    envVars:
      - key: SECRET_KEY
        fromService:
          name: alx-project-nexus-web
          type: web
          property: envVars.SECRET_KEY
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: alx-project-nexus-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: alx-project-nexus-redis
          type: redis
          property: connectionString
      - key: CACHE_URL
        fromService:
          name: alx-project-nexus-redis
          type: redis
          property: connectionString

  # Shared Redis
  - type: redis
    name: alx-project-nexus-redis
    ipAllowList: []  # private connection

databases:
  - name: alx-project-nexus-db
    databaseName: nexusdb
    user: nexususer
